version: "3.9"

services:

  reverse-proxy:
    build: reverse_proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./certs:/certs

  api:
    build: api
    environment:
      USERNAME: tom
      PASSWORD: password
    expose:
      - 50051